### ISSUE TITLE
Should be consistent with decorator naming

### ISSUE THREAD

**Issue by Martin-Cox** [bencoveney/ts-function-docs#4]
Current @ignore decorator for params is too generic:
- In a large codebase it could conflict with an existing decorator
- It doesn't really tell us anything about what the decorator actually does (what ignores it?)

I suggest all of the documentation decorators should be prefixed with a common name e.g. `@doc...`:

```
/**
 * Class documentation
 */
export class documentedClass {
    /**
     * This one generates documentation
     */
    @docGenerate()
    public static documentedFunction(@docIgnore sample: string, sample2: number) {
        console.log("Hello World");
    }
}
```

Any suggestions for a better prefix (or better way of denoting the documentation decorators) are welcome

**Comment by bencoveney** [comment]
Sounds good to me 👍

A couple of alternatives we could consider:
- Could use an existing JSDoc tag e.g. ([ignore?](http://usejsdoc.org/tags-ignore.html) - not sure we could combine these with the @param tag though.
- Could use a custom JSDoc tag AKA [plugin](http://usejsdoc.org/about-plugins.html).
- Could allow the user to define a function to test which parameters to ignore - so ignoring certain decorators (or parameters for other reasons) is up to them.
